while _G.Farming do wait()
for i,v in pairs(game:GetService("Workspace"):GetChildren()) do
if game.Players.LocalPlayer.Character and v:FindFirstChild("HumanoidRootPart") and v:FindFirstChild("Humanoid") then
if string.match(v.Name, "Santa Clone") and v.Humanoid.Health > 0 then
repeat wait()
   -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Itsahalloweeen"
}

game:GetService("Players").LocalPlayer.Character.CombatV1.CombatRemote:FireServer(unpack(args))

game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = v.HumanoidRootPart.CFrame * CFrame.Angles(30,0,0) + Vector3.new(0, 10, 0) 
game.Players.LocalPlayer.Character.Humanoid:ChangeState(11)
until _G.Farming == false or v.Humanoid.Health == 0 
end
end
end
end

